### ISSUE TITLE
rake task:  Couldn't get access token.  Server returned 401: Unauthorized.

### ISSUE THREAD

**Issue by Olgagr** [robin850/carrierwave-dropbox#15]
I created app in Dropbox with app folder permission type. When I run rake task:

```
rake dropbox:authorize APP_KEY=xxx APP_SECRET=xxx ACCESS_TYPE=app_folder
```

I get an error:

```
Visit this URL: https://www.dropbox.com/1/oauth/authorize?oauth_token=kECiTB7Su081iODs
And after you approved the authorization confirm it here (y/n): y
W, [2014-07-29T09:11:36.501940 #31832]  WARN -- : ** [Bugsnag] No API key configured, couldn't notify
rake aborted!
DropboxAuthError: Couldn't get access token.  Server returned 401: Unauthorized.
/Users/ograbek/.rvm/gems/ruby-2.1.2@uke_geocoder/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:263:in `get_token'
/Users/ograbek/.rvm/gems/ruby-2.1.2@uke_geocoder/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:337:in `get_access_token'
/Users/ograbek/.rvm/gems/ruby-2.1.2@uke_geocoder/gems/carrierwave-dropbox-1.2.1/lib/carrierwave/dropbox/rake.rb:17:in `authorize'
/Users/ograbek/.rvm/gems/ruby-2.1.2@uke_geocoder/gems/carrierwave-dropbox-1.2.1/lib/carrierwave/dropbox/authorize.rake:11:in `block (2 levels) in <top (required)>'
```

Key and secret are correct. When I visited this URL:

```
https://www.dropbox.com/1/oauth/authorize?oauth_token=kECiTB7Su081iODs
```

I could be able to authorize access. Should I do something more ?

**Comment by robin850** [comment]
Okay, just pushed [a commit](https://github.com/robin850/carrierwave-dropbox/commit/7f455817cd2f426547e552229981e1f824ef6188) crediting you in order to fix that, thanks! :-)
