### ISSUE TITLE
Image retrieve

### ISSUE THREAD

**Issue by tochman** [robin850/carrierwave-dropbox#8]
Hi,

I'm using `app_folder` as access type for my app. Everything works fine when I upload files but I get a not found-error when I retrieve the files. 

```
2013-12-28T10:45:36.275665+00:00 app[web.1]:   Parameters: {"id"=>"1"}
2013-12-28T10:45:36.646307+00:00 app[web.1]: Completed 500 Internal Server Error in 370ms
2013-12-28T10:45:36.649752+00:00 app[web.1]: app/controllers/application_controller.rb:61:in `minis'
2013-12-28T10:45:36.649752+00:00 app[web.1]: 
2013-12-28T10:45:36.649752+00:00 app[web.1]: DropboxError (Path '/uploads/mini_avatar-1.jpg' not found):
2013-12-28T10:45:36.649752+00:00 app[web.1]: 
2013-12-28T10:45:36.649752+00:00 app[web.1]: 
2013-12-28T10:45:36.652352+00:00 app[web.1]:   Parameters: {"id"=>"1"}
2013-12-28T10:45:36.652272+00:00 app[web.1]: Processing by ErrorsController#server_error as HTML
2013-12-28T10:45:37.014834+00:00 app[web.1]: Completed 500 Internal Server Error in 362ms
2013-12-28T10:45:37.014904+00:00 app[web.1]: Error during failsafe response: Path '/uploads/mini_avatar-1.jpg' not found
2013-12-28T10:45:37.014904+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.0.0/gems/dropbox-sdk-1.6.3/lib/dropbox_sdk.rb:111:in `parse_response'
2013-12-28T10:45:37.014904+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.0.0/gems/carrierwave-dropbox-1.1.1/lib/carrierwave/storage/dropbox.rb:60:in `url'
...
```

The path to that specific file should be (or was) `https://dl.dropboxusercontent.com/1/view/qi6swqn3o11u6vq/Apps/AgileVentures/production/user/1/avatar-1.jpg` so I assume that `'ulr'` should be `...production/user/1/avatar-1.jpg`

This is from production env on Heroku. http://websiteone.herokuapp.com/ , but I have same issues on my local machine as well. 

My `@client.media(path)["url"]` outputs: 
 `!! #<DropboxError: Path '/uploads/mini_avatar-4.jpg' not found>``

My question is if the url is set and stored properly by the gem or if I'm doing something wrong.

**Comment by rdosramos** [comment]
Having the same problem here, any ideas?
